app: hgpoker-api
service: hgpoker-api

package:
  exclude:
    - .github/**
    - node_modules/**
    - package.json
    - package-lock.json
    - README.md
    - requirements.txt
    - venv/**
  excludeDevDependencies: false

plugins:
  - serverless-python-requirements

provider:
  apiGateway:
    binaryMediaTypes:
      - multipart/form-data
  lambdaHashingVersion: 20201221
  name: aws
  region: us-east-2
  runtime: python3.8
  stage: dev
  tracing:
    lambda: true

functions:
  lambda:
    environment:
      DATABASE_HOST: hgpoker.c13gml6mujwk.us-east-2.rds.amazonaws.com
      DATABASE_NAME: hgpoker
      DATABASE_PASSWORD: pass-hgpoker
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres

    events:
      - http: ANY /
      - http: ANY /{proxy+}
    handler: hgpoker-api.handler
    memorySize: 1024
    name: hgpoker-api-dev
    timeout: 120

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        Name: hgpoker-api-dev
      Type: AWS::ApiGateway::RestApi
