app: hgpoker-api
service: hgpoker-api

package:
  exclude:
    - .github/**
    - node_modules/**
    - package.json
    - package-lock.json
    - README.md
    - requirements.txt
    - venv/**
  excludeDevDependencies: false

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-plugin-create-deployment-bucket

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    useDownloadCache: false
  s3_bucket_deploy: hgpoker-api-${opt:stage}
  wsgi:
    app: main.application
    packRequirements: false


provider:
  apiGateway:
    binaryMediaTypes:
      - multipart/form-data
  lambdaHashingVersion: 20201221
  name: aws
  region: us-east-2
  runtime: python3.8
  tracing:
    lambda: true

functions:
  lambda:
    environment:
      DATABASE_HOST:
      DATABASE_NAME:
      DATABASE_PASSWORD:
      DATABASE_PORT:
      DATABASE_USERNAME:

    events:
      - http: ANY /
      - http: ANY /{proxy+}
    handler: wsgi_handler.handler
    memorySize: 128
    name: hgpoker-api-${opt:stage}
    timeout: 30

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        Name: hgpoker-api-dev
      Type: AWS::ApiGateway::RestApi
