app: cropland-api
service: cropland-api

package:
  exclude:
    - .github/**
    - node_modules/**
    - package.json
    - package-lock.json
    - README.md
    - requirements.txt
    - venv/**
  excludeDevDependencies: false

plugins:
  - serverless-plugin-create-deployment-bucket
  - serverless-python-requirements
  - serverless-wsgi

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    useDownloadCache: false
  s3_bucket_deploy: cropland-api-${opt:stage}
  wsgi:
    app: main.application
    packRequirements: false

provider:
  apiGateway:
    binaryMediaTypes:
      - multipart/form-data
  deploymentBucket:
    blockPublicAccess: true
    name: ${self:custom.s3_bucket_deploy}
    serverSideEncryption: AES256
  lambdaHashingVersion: 20201221
  name: aws
  region: ${opt:region}
  runtime: python3.8
  stage: ${opt:stage}
  tracing:
    lambda: true

functions:
  lambda:
    environment:
      APPLICATION_DEBUG: ${ssm:/cropland-api-application-debug~true}
      APPLICATION_HOST: ${ssm:/cropland-api-application-host~true}
      APPLICATION_PORT: ${ssm:/cropland-api-application-port~true}
      AWS_COGNITO_AUTH_FLOW: ${ssm:/cropland-api-aws-cognito-auth-flow~true}
      AWS_COGNITO_CLIENT_ID: ${ssm:/cropland-api-aws-cognito-client-id~true}
      AWS_COGNITO_USER_POOL_ID: ${ssm:/cropland-api-aws-cognito-user-pool-id~true}
      AWS_S3_BUCKET: ${ssm:/cropland-api-aws-s3-bucket~true}
      AWS_S3_BUCKET_EXPORT: ${ssm:/cropland-api-aws-s3-bucket-export~true}
      AWS_SQS_QUEUE: ${ssm:/cropland-api-aws-sqs-queue~true}
      AWS_SQS_QUEUE_ONBOARDING: ${ssm:/cropland-api-aws-sqs-queue-onboarding~true}
      DATABASE_HOST: ${ssm:/cropland-api-database-host~true}
      DATABASE_MAX_CONNECTION: ${ssm:/cropland-api-database-max-connection~true}
      DATABASE_NAME: ${ssm:/cropland-api-database-name~true}
      DATABASE_PASSWORD: ${ssm:/cropland-api-database-password~true}
      DATABASE_PORT: ${ssm:/cropland-api-database-port~true}
      DATABASE_PRINT_SQL: ${ssm:/cropland-api-database-print-sql~true}
      DATABASE_USERNAME: ${ssm:/cropland-api-database-username~true}
      FLASK_ENV: ${ssm:/cropland-api-flask-env~true}
      PASSWORD_DEFAULT_COGNITO: ${ssm:/cropland-api-password-default-cognito~true}
      SMTP_EMAIL: ${ssm:/cropland-api-smtp-email~true}
      SMTP_HOST: ${ssm:/cropland-api-smtp-host~true}
      SMTP_PASSWORD: ${ssm:/cropland-api-smtp-password~true}
      SMTP_PORT: ${ssm:/cropland-api-smtp-port~true}
      SQLALCHEMY_DATABASE_URI: ${ssm:/cropland-api-sqlalchemy-database-uri~true}

    events:
      - http: ANY /
      - http: ANY /{proxy+}
    handler: wsgi_handler.handler
    memorySize: 1024
    name: cropland-api-${opt:stage}
    timeout: 120

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        Name: cropland-api-${opt:stage}
      Type: AWS::ApiGateway::RestApi
