name: Main

on:
  push:
    branches:
      - main

jobs:
#  quality-assurance:
#    name: quality-assurance
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: docker://sonarsource/sonar-scanner-cli:latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  deploy:
    name: deploy
    runs-on: ubuntu-latest
#    needs: quality-assurance
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Tag the Image
        run: |
          docker build --no-cache -t mew .
      - name: Build, Tag, and Push Image to Amazon ECR
        run: |
          docker tag mew:latest 753007467993.dkr.ecr.us-east-1.amazonaws.com/cropland-api:latest
          docker push 753007467993.dkr.ecr.us-east-1.amazonaws.com/cropland-api:latest
      - name: Update Service Cropland
        run: |
          aws ecs update-service --force-new-deployment --service svc-api-cropland --cluster cl-cropland
      - name: Update Service AgroAmazonia
        run: |
          aws ecs update-service --force-new-deployment --service svc-api-agroamazonia --cluster cl-agroamazonia
