name: Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Deploy Project
        run: |
          npm install -g serverless serverless-python-requirements serverless-wsgi serverless-plugin-create-deployment-bucket
      - name: Serverless AWS Authentication
        run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy Lambda Function
        run: serverless deploy --region ${{ secrets.AWS_REGION }} --stage dev
